# Container for training things with a few additional dev tools (e.g. jupyter)
FROM nvcr.io/nvidia/cuda:12.0.1-devel-ubuntu22.04

RUN chmod 1777 /tmp/ && apt-get -y update && apt-get -y install python3-dev python3-pip python3-wheel python3-setuptools-whl python3-packaging python3-venv git wget unzip nano

WORKDIR /workspace
RUN python3 -m venv .venv
ENV PATH="/workspace/.venv/bin:$PATH"

RUN pip install torch packaging setuptools wheel
RUN ln -s /usr/lib/x86_64-linux-gnu/libcuda.so.1 /usr/lib/x86_64-linux-gnu/libcuda.so

RUN wget https://github.com/facebookresearch/fastText/archive/v0.9.2.zip \
  && unzip v0.9.2.zip \
  && cd fastText-0.9.2 \
  && make -j 8\
  && cp fasttext /usr/local/bin/ \
  && cd /workspace \
  && rm -r /workspace/fastText-0.9.2

COPY requirements-dev.txt  ./
RUN pip install -r requirements-dev.txt
CMD /bin/bash
